version: '3'

services:
  redis:
    image: redis:6.2.11
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis-data:/data
    networks:
        - backend

  db:
    image: postgres:15.2
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    networks:
        - backend

networks:
    backend:
