service: serverless-naruhodoo

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-2
  profile: ${env:AWS_PROFILE}
  stage: ${opt:stage, 'dev'}

functions:
  hello:
    handler: src/app/handler.hello
    events:
      - http:
          path: /hello
          method: get

plugins:
  - serverless-python-requirements
  - serverless-domain-manager

custom:
  customDomain:
    domainName: ${env:CUSTOM_DOMAIN}
    stage: ${self:provider.stage}
    basePath: ${self:provider.stage}
    certificateName: ${env:CERTIFICATE_NAME}
    createRoute53Record: true