service: serverless-naruhodoo

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-2
  profile: ${env:AWS_PROFILE}
  stage: ${opt:stage, 'dev'}

  iam.role.statements:
    - Effect: Allow
      Action:
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminDeleteUser
        - cognito-idp:AdminGetUser
        - cognito-idp:AdminUpdateUserAttributes
      Resource: '*'

functions:
  hello:
    handler: functions/handler.hello
    events:
      - http:
          path: /hello
          method: get

  kakao_signin:
    handler: functions/app.kakao_login
    events:
      - http:
          path: /login/kakao
          method: get

plugins:
  - serverless-python-requirements
  - serverless-domain-manager
  - serverless-offline

custom:
  customDomain:
    domainName: ${env:CUSTOM_DOMAIN}
    stage: ${self:provider.stage}
    basePath: ${self:provider.stage}
    certificateName: ${env:CERTIFICATE_NAME}
    createRoute53Record: true