service: serverless-naruhodoo

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-2
  profile: ${env:AWS_PROFILE}
  stage: ${opt:stage, 'dev'}

functions:
  login:
    handler: functions/handler.login
    events:
      - http:
          path: /login
          method: get

  kakao_login:
    handler: functions/handler.kakao_login
    events:
      - http:
          path: /login/kakao
          method: get

  process:
    handler: functions/handler.process
    events:
      - http:
          path: /login/process
          method: get

  get_nickname:
    handler: functions/handler.nickname
    events:
      - http:
          path: /profile/nickname
          method: get

  google_login:
    handler: functions/handler.google_login
    events:
      - http:
          path: login/google
          method: get

  cognito_login:
    handler: functions/handler.cognito_login
    events:
      - http:
          path: /login/cognito
          method: get

  logout:
    handler: functions/handler.logout
    events:
      - http:
          path: /logout
          method: get

  delete_account:
    handler: functions/handler.delete_account
    events:
      - http:
          path: /profile
          method: delete

plugins:
  - serverless-python-requirements
  - serverless-domain-manager
  - serverless-offline

custom:
  customDomain:
    domainName: ${env:CUSTOM_DOMAIN}
    stage: ${self:provider.stage}
    basePath: ${self:provider.stage}
    certificateName: ${env:CERTIFICATE_NAME}
    createRoute53Record: true
