name: Frontend CI/CD

on:
    push:
        branches:
            - master
        paths:
            - "frontend/**"

frontend-build-deploy:
    runs-on: ubuntu-latest
    environment: frontend-env
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
              node-version: "14"

        - name: Build Static Files
          working-directory: ./frontend
          run: npm run build

        - name: Install AWS CLI
          run: |
              sudo apt update
              sudo apt install -y python3-pip
              pip3 install awscli --upgrade --user

        - name: Deploy to S3
          working-directory: ./frontend
          run: |
              aws s3 sync frontend/build s3://${{ env.AWS_BUCKET_NAME }} --delete
